In [60]:
metric = tfa.metrics.F1Score(num_classes=3, threshold=0.5,)
y_true = np.array([[1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1]], np.int32)
y_pred = np.array([[0.8, 0.6, 0.7],
                   [0.6, 0.6, 0.6],
                   [0.6, 0.6, 0.8]], np.float32)
metric.update_state(y_true, y_pred)
result = metric.result()
result.numpy()

array([0.5, 0.5, 0.5], dtype=float32)

In [58]:
import numpy as np
import tensorflow_addons as tfa

# if multiclass input is provided

y_true = np.array([[1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1]], np.int32)
y_pred = np.array([[0.8, 0.6, 0.7],
                   [0.6, 0.6, 0.6],
                   [0.6, 0.6, 0.8]], np.float32)
metric = tfa.metrics.MultiLabelConfusionMatrix(num_classes=3)
metric.update_state(y_true, y_pred.round())
result = metric.result()
result.numpy() #doctest: -DONT_ACCEPT_BLANKLINE




array([[[0., 2.],
        [0., 1.]],

       [[0., 2.],
        [0., 1.]],

       [[0., 2.],
        [0., 1.]]], dtype=float32)

In [59]:
metric = tfa.metrics.F1Score(num_classes=3)
metric.update_state(y_true, y_pred)
result = metric.result()
result.numpy()


array([0.6666667, 1.       , 0.6666667], dtype=float32)

In [56]:
from esmart.util.metric import RecallMultiClass
import numpy as np

metric = RecallMultiClass(num_classes=3)

metric.update_state(y_true, y_pred)
result = metric.result()
result.numpy()

array([1., 1., 1.], dtype=float32)

In [57]:
from esmart.util.metric import PrecisionMultiClass
import numpy as np

metric = PrecisionMultiClass(num_classes=3)

metric.update_state(y_true, y_pred)
result = metric.result()
result.numpy()

array([0.5, 1. , 0.5], dtype=float32)